// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	playSound: (path: string, volume: number | null, speed: number | null) => typedError<number, string>(__TAURI_INVOKE("play_sound", { path, volume, speed })),
	pauseSound: (id: number) => __TAURI_INVOKE<void>("pause_sound", { id }),
	resumeSound: (id: number) => __TAURI_INVOKE<void>("resume_sound", { id }),
	stopSound: (id: number) => __TAURI_INVOKE<void>("stop_sound", { id }),
	seekSound: (id: number, secs: number | null) => __TAURI_INVOKE<void>("seek_sound", { id, secs }),
	setGeneralVolume: (volume: number | null) => __TAURI_INVOKE<void>("set_general_volume", { volume }),
	setVolume: (id: number, volume: number | null) => __TAURI_INVOKE<void>("set_volume", { id, volume }),
	stopAllSounds: () => __TAURI_INVOKE<void>("stop_all_sounds"),
	getProgress: (id: number) => __TAURI_INVOKE<{
	current: number,
	total: number,
} | null>("get_progress", { id }),
	getActiveSounds: () => __TAURI_INVOKE<number[]>("get_active_sounds"),
	setPlaybackSpeed: (id: number, speed: number | null) => __TAURI_INVOKE<void>("set_playback_speed", { id, speed }),
	getMicVolume: () => __TAURI_INVOKE<number | null>("get_mic_volume"),
	setMicVolume: (volume: number | null) => __TAURI_INVOKE<void>("set_mic_volume", { volume }),
	getMicPitch: () => __TAURI_INVOKE<number | null>("get_mic_pitch"),
	setMicPitch: (semitones: number | null) => __TAURI_INVOKE<void>("set_mic_pitch", { semitones }),
	stopMic: () => __TAURI_INVOKE<void>("stop_mic"),
	getAudioApps: () => typedError<AudioApp[], string>(__TAURI_INVOKE("get_audio_apps")),
	setForwardVolume: (id: number, volume: number | null) => typedError<null, string>(__TAURI_INVOKE("set_forward_volume", { id, volume })),
	stopForward: (id: number) => typedError<null, string>(__TAURI_INVOKE("stop_forward", { id })),
	forwardApp: (pid: number) => typedError<number, string>(__TAURI_INVOKE("forward_app", { pid })),
	getHotkeys: () => __TAURI_INVOKE<HotKeyEntry[]>("get_hotkeys"),
	registerHotkey: (hk: HotKeyEntry) => typedError<string, string>(__TAURI_INVOKE("register_hotkey", { hk })),
	updateHotkey: (hk: HotKeyEntry) => typedError<string, string>(__TAURI_INVOKE("update_hotkey", { hk })),
	unregisterHotkey: (id: string) => typedError<null, string>(__TAURI_INVOKE("unregister_hotkey", { id })),
	markAsReady: () => typedError<null, string>(__TAURI_INVOKE("mark_as_ready")),
	onboard: () => typedError<null, string>(__TAURI_INVOKE("onboard")),
	isOnboarded: () => __TAURI_INVOKE<boolean>("is_onboarded"),
	getTabs: () => __TAURI_INVOKE<([Tab, SoundFile[]])[]>("get_tabs"),
	getTab: (id: string) => __TAURI_INVOKE<[Tab, SoundFile[]] | null>("get_tab", { id }),
	addTab: (name: string, kind: TabKind, path: string | null) => __TAURI_INVOKE<void>("add_tab", { name, kind, path }),
	editTab: (tab: Tab) => __TAURI_INVOKE<void>("edit_tab", { tab }),
	removeTab: (id: string) => __TAURI_INVOKE<void>("remove_tab", { id }),
	moveTab: (id: string, idx: number) => __TAURI_INVOKE<void>("move_tab", { id, idx }),
	getCustomCss: () => typedError<string, string>(__TAURI_INVOKE("get_custom_css")),
	saveCustomCss: (css: string) => typedError<null, string>(__TAURI_INVOKE("save_custom_css", { css })),
	setAutostart: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_autostart", { enabled })),
	getAutostart: () => typedError<boolean, string>(__TAURI_INVOKE("get_autostart")),
	getNormalize: () => __TAURI_INVOKE<boolean>("get_normalize"),
	setNormalize: (normalize: boolean) => typedError<null, string>(__TAURI_INVOKE("set_normalize", { normalize })),
	getVolume: () => __TAURI_INVOKE<number | null>("get_volume"),
	getSoundConfig: (key: string) => __TAURI_INVOKE<{
	/**  Tags associated with the sound. */
	tags: string[],
	/**  List of tabs that the sound is pinned to. */
	pins: string[],
} | null>("get_sound_config", { key }),
	setSoundConfig: (key: string, config: SoundConfig) => typedError<null, string>(__TAURI_INVOKE("set_sound_config", { key, config })),
	getSoundsConfig: () => __TAURI_INVOKE<{ [key in string]: SoundConfig }>("get_sounds_config"),
	clearAllCache: () => typedError<null, string>(__TAURI_INVOKE("clear_all_cache")),
	getSoundsHistory: () => typedError<string[], string>(__TAURI_INVOKE("get_sounds_history")),
};

/** Events */
export const events = {
	alertDismissEvent: makeEvent<AlertDismissEvent>("alert-dismiss-event"),
	alertEvent: makeEvent<AlertEvent>("alert-event"),
};

/* Types */
/**  Represents an alert to be displayed in the UI. */
export type Alert = {
	kind: AlertKind,
	title: string,
	message: string,
};

/**  Event emitted when an alert is dismissed. */
export type AlertDismissEvent = string;

/**  Event emitted when an alert is displayed. */
export type AlertEvent = Alert;

/**  Kind of the [`Alert`]. */
export type AlertKind = "Error" | "Warn";

/**  Representation of an audio app for forwarding. */
export type AudioApp = {
	id: number,
	name: string,
	/**  Base64 encoded icon */
	icon: string | null,
};

/**  Represents a hotkey entry. */
export type HotKeyEntry = {
	id: string,
	binding: string,
	kind: HotKeyKind,
	context: string,
};

/**  Hotkey kind */
export type HotKeyKind = 
/**  For playing a sound */
"Sound" | 
/**  For controling playback and microphone (global only) */
"Control";

/**  Progress of a sound. */
export type Progress = {
	current: number,
	total: number,
};

/**  Representation of the customisation for the sound, use path as key. */
export type SoundConfig = {
	/**  Tags associated with the sound. */
	tags: string[],
	/**  List of tabs that the sound is pinned to. */
	pins: string[],
};

/**  Represents a sound file in a tab. */
export type SoundFile = {
	path: string,
	size: number,
	datetime: number,
	duration: number,
};

/**  Represents a tab in the dashboard tab. */
export type Tab = {
	id: string,
	kind: TabKind,
	name: string,
	path: string | null,
	sounds: string[],
};

/**  Kind of the [`Tab`]. */
export type TabKind = "directory" | "user" | "favourite";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

