
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async playSound(path: string, volume: number | null, speed: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_sound", { path, volume, speed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseSound(id: number) : Promise<void> {
    await TAURI_INVOKE("pause_sound", { id });
},
async resumeSound(id: number) : Promise<void> {
    await TAURI_INVOKE("resume_sound", { id });
},
async stopSound(id: number) : Promise<void> {
    await TAURI_INVOKE("stop_sound", { id });
},
async seekSound(id: number, secs: number) : Promise<void> {
    await TAURI_INVOKE("seek_sound", { id, secs });
},
async setGeneralVolume(volume: number) : Promise<void> {
    await TAURI_INVOKE("set_general_volume", { volume });
},
async setVolume(id: number, volume: number) : Promise<void> {
    await TAURI_INVOKE("set_volume", { id, volume });
},
async stopAllSounds() : Promise<void> {
    await TAURI_INVOKE("stop_all_sounds");
},
async getProgress(id: number) : Promise<Progress | null> {
    return await TAURI_INVOKE("get_progress", { id });
},
async getActiveSounds() : Promise<number[]> {
    return await TAURI_INVOKE("get_active_sounds");
},
async setPlaybackSpeed(id: number, speed: number) : Promise<void> {
    await TAURI_INVOKE("set_playback_speed", { id, speed });
},
async getMicVolume() : Promise<number> {
    return await TAURI_INVOKE("get_mic_volume");
},
async setMicVolume(volume: number) : Promise<void> {
    await TAURI_INVOKE("set_mic_volume", { volume });
},
async getMicPitch() : Promise<number> {
    return await TAURI_INVOKE("get_mic_pitch");
},
async setMicPitch(semitones: number) : Promise<void> {
    await TAURI_INVOKE("set_mic_pitch", { semitones });
},
async stopMic() : Promise<void> {
    await TAURI_INVOKE("stop_mic");
},
async getAudioApps() : Promise<Result<AudioApp[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_apps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setForwardVolume(id: number, volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_forward_volume", { id, volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopForward(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_forward", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async forwardApp(pid: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forward_app", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHotkeys() : Promise<HotKeyEntry[]> {
    return await TAURI_INVOKE("get_hotkeys");
},
async registerHotkey(hk: HotKeyEntry) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_hotkey", { hk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHotkey(hk: HotKeyEntry) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_hotkey", { hk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unregisterHotkey(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unregister_hotkey", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markAsReady() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_as_ready") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async onboard() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboard") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isOnboarded() : Promise<boolean> {
    return await TAURI_INVOKE("is_onboarded");
},
async getTabs() : Promise<([Tab, SoundFile[]])[]> {
    return await TAURI_INVOKE("get_tabs");
},
async getTab(id: string) : Promise<[Tab, SoundFile[]] | null> {
    return await TAURI_INVOKE("get_tab", { id });
},
async addTab(name: string, kind: TabKind, path: string | null) : Promise<void> {
    await TAURI_INVOKE("add_tab", { name, kind, path });
},
async editTab(tab: Tab) : Promise<void> {
    await TAURI_INVOKE("edit_tab", { tab });
},
async removeTab(id: string) : Promise<void> {
    await TAURI_INVOKE("remove_tab", { id });
},
async moveTab(id: string, idx: number) : Promise<void> {
    await TAURI_INVOKE("move_tab", { id, idx });
},
async getCustomCss() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_custom_css") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveCustomCss(css: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_custom_css", { css }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutostart(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_autostart", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAutostart() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_autostart") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNormalize() : Promise<boolean> {
    return await TAURI_INVOKE("get_normalize");
},
async setNormalize(normalize: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_normalize", { normalize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVolume() : Promise<number> {
    return await TAURI_INVOKE("get_volume");
},
async getSoundConfig(key: string) : Promise<SoundConfig | null> {
    return await TAURI_INVOKE("get_sound_config", { key });
},
async setSoundConfig(key: string, config: SoundConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sound_config", { key, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSoundsConfig() : Promise<Partial<{ [key in string]: SoundConfig }>> {
    return await TAURI_INVOKE("get_sounds_config");
},
async clearAllCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSoundsHistory() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sounds_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
alertDismissEvent: AlertDismissEvent,
alertEvent: AlertEvent
}>({
alertDismissEvent: "alert-dismiss-event",
alertEvent: "alert-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Represents an alert to be displayed in the UI.
 */
export type Alert = { kind: AlertKind; title: string; message: string }
/**
 * Event emitted when an alert is dismissed.
 */
export type AlertDismissEvent = string
/**
 * Event emitted when an alert is displayed.
 */
export type AlertEvent = Alert
/**
 * Kind of the [`Alert`].
 */
export type AlertKind = "Error" | "Warn"
/**
 * Representation of an audio app for forwarding.
 */
export type AudioApp = { id: number; name: string; 
/**
 * Base64 encoded icon
 */
icon: string | null }
/**
 * Represents a hotkey entry.
 */
export type HotKeyEntry = { id: string; binding: string; kind: HotKeyKind; context: string }
/**
 * Hotkey kind
 */
export type HotKeyKind = 
/**
 * For playing a sound
 */
"Sound" | 
/**
 * For controling playback and microphone (global only)
 */
"Control"
/**
 * Progress of a sound.
 */
export type Progress = { current: number; total: number }
/**
 * Representation of the customisation for the sound, use path as key.
 */
export type SoundConfig = { 
/**
 * Tags associated with the sound.
 */
tags: string[]; 
/**
 * List of tabs that the sound is pinned to.
 */
pins: string[] }
/**
 * Represents a sound file in a tab.
 */
export type SoundFile = { path: string; size: number; datetime: number; duration: number }
/**
 * Represents a tab in the dashboard tab.
 */
export type Tab = { id: string; kind: TabKind; name: string; path: string | null; sounds: string[] }
/**
 * Kind of the [`Tab`].
 */
export type TabKind = "directory" | "user" | "favourite"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
